### ISSUE TITLE
Avoid usage of @Value Spring annotation

### ISSUE THREAD

**Issue by apupier** [obsidian-toaster-quickstarts/quick_rest_springboot-tomcat#13]
It seems that a SpringBoot committer is not recommending to use the @Value annotation: http://stackoverflow.com/questions/32058814/spring-boot-custom-variables-in-application-properties

I personally have no idea of what is the best.
I just hit it because the way recommended by Stephane Nicoll avoids to have the warning in Spring IDE.

**Comment by cmoulliard** [comment]
@apupier Thanks for the info. I will have a look next week. They don't also use the @Value in their example --> https://github.com/spring-guides/gs-rest-service/blob/master/complete/src/main/java/hello/GreetingController.java#L12

**Comment by cmoulliard** [comment]
See -> https://issues.jboss.org/browse/OBST-37
